CREATE TABLE users (
	id INT PRIMARY KEY AUTO_INCREMENT,
	display_name VARCHAR(35) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	refresh_token TEXT DEFAULT NULL,
	bio TEXT DEFAULT NULL,
	photo_url TEXT DEFAULT NULL,
	background_url TEXT DEFAULT NULL,
	role ENUM ('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
	token_version INT NOT NULL DEFAULT 0,
	created_at DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE media (
	id INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	path TEXT NOT NULL,
	content_type VARCHAR(100) NOT NULL,
	size INT NOT NULL,
	created_at DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE posts (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	created_at DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DateTime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	user_id INT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users (id)
);
